spring :
  datasource:
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: Jeeva@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
